version: "3.9"

services:
  # ASP.NET Service
  api:
    build:
      context: ./api
    ports:
      - 5257:5257
      - 7201:7201
    expose:
      - 5257
    env_file:
      - .env.api
    volumes:
      - ./api:/src
    networks:
      - prac-hris
    depends_on:
      - db

  # NextJS Service
  client:
    build:
      context: ./client
    ports:
      - 3000:3000
    env_file:
      - .env.client
    networks:
      - prac-hris
    depends_on:
      - api
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

  # MSSQL Service
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: root
    ports:
      - 1433:1433
    restart: always
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    env_file:
      - .env.db
    networks:
      - prac-hris

  # Nginx service
  webserver:
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
    networks:
      - prac-hris
    restart: always

  # Certbot Srevice
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email abduljalil.palala@sun-asterisk.com -d sun-hris.org --agree-tos
    networks:
      - prac-hris
networks:
  prac-hris:
    driver: bridge
